/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ljse.cmjd31.inventorycontrolsystem.view.item;

import com.ijse.cmjd31.inventorycontrolsystem.controller.AuthorController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.BookController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.CategoryController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.ItemController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.LanguageController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.SupplierController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.publisherController;
import com.ijse.cmjd31.inventorycontrolsystem.model.Author;
import com.ijse.cmjd31.inventorycontrolsystem.model.Book;
import com.ijse.cmjd31.inventorycontrolsystem.model.Category;
import com.ijse.cmjd31.inventorycontrolsystem.model.Item;
import com.ijse.cmjd31.inventorycontrolsystem.model.Language;
import com.ijse.cmjd31.inventorycontrolsystem.model.Publisher;
import com.ijse.cmjd31.inventorycontrolsystem.model.Supplier;
import com.ijse.cmjd31.inventorycontrolsystem.other.IdGenerator;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.AddAuthorForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.AddCategoryForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.AddLanguageForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.AddPublisherForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.ManagePublisherForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.ManageCategoryForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.ManageLanguageForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.ManagePublisherForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.supplier.AddSupplierForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.supplier.ManageSupplierForm;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author 1
 */
public class AddItemForm extends javax.swing.JPanel {

    /**
     * Creates new form ItemAdd
     */
    private boolean b;

    public AddItemForm() {

        initComponents();
        try {
            fillCategoryCombo();
            fillLanguageCombo();
            fillAuthorCombo();
            fillPublisherCombo();
            fillSupplierCombo();
        } catch (SQLException ex) {
            Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        String nextId;
        try {
            nextId = IdGenerator.getNextId("Item", "idItem", "I");
            itemText.setText(nextId);
        } catch (SQLException ex) {
            Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        descriptionText.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        itemText = new javax.swing.JTextField();
        itemLabel = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        bookLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        titleText = new javax.swing.JTextField();
        categoryCombo = new javax.swing.JComboBox();
        languageLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        languageCombo = new javax.swing.JComboBox();
        authorCombo = new javax.swing.JComboBox();
        publisherCombo = new javax.swing.JComboBox();
        categoryButton = new javax.swing.JButton();
        languageButton = new javax.swing.JButton();
        publisherButton = new javax.swing.JButton();
        authorButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bookIdText = new javax.swing.JTextField();
        supplierLabel = new javax.swing.JLabel();
        supCombo = new javax.swing.JComboBox();
        costLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        costText = new javax.swing.JTextField();
        salesText = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        reOrderLabel = new javax.swing.JLabel();
        qtyText = new javax.swing.JTextField();
        reOrderText = new javax.swing.JTextField();
        discountText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        supplierButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        setPreferredSize(new java.awt.Dimension(880, 620));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setNextFocusableComponent(descriptionText);
        jPanel5.setPreferredSize(new java.awt.Dimension(900, 620));
        jPanel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel5KeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Details", 0, 0, null, new java.awt.Color(0, 51, 102)));
        jPanel2.setNextFocusableComponent(descriptionText);

        itemText.setEditable(false);
        itemText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTextActionPerformed(evt);
            }
        });
        itemText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemTextKeyReleased(evt);
            }
        });

        itemLabel.setText("Item Code");

        descriptionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextActionPerformed(evt);
            }
        });
        descriptionText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionTextKeyReleased(evt);
            }
        });

        descriptionLabel.setText("Description");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Book Detail", 0, 0, null, new java.awt.Color(0, 51, 102)));

        categoryLabel.setText("Category");

        bookLabel.setText("Book Title");

        authorLabel.setText("Author");

        titleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextActionPerformed(evt);
            }
        });
        titleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleTextKeyReleased(evt);
            }
        });

        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboActionPerformed(evt);
            }
        });
        categoryCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                categoryComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                categoryComboKeyReleased(evt);
            }
        });

        languageLabel.setText("Language");

        publisherLabel.setText("Publisher");

        languageCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        languageCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboActionPerformed(evt);
            }
        });
        languageCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                languageComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                languageComboKeyReleased(evt);
            }
        });

        authorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        authorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorComboActionPerformed(evt);
            }
        });
        authorCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                authorComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                authorComboKeyReleased(evt);
            }
        });

        publisherCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        publisherCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherComboActionPerformed(evt);
            }
        });
        publisherCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                publisherComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                publisherComboKeyReleased(evt);
            }
        });

        categoryButton.setBackground(new java.awt.Color(204, 204, 204));
        categoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-new-7.png"))); // NOI18N
        categoryButton.setText("New- F1");
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });
        categoryButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                categoryButtonKeyReleased(evt);
            }
        });

        languageButton.setBackground(new java.awt.Color(204, 204, 204));
        languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-new-7.png"))); // NOI18N
        languageButton.setText("New - F2");
        languageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageButtonActionPerformed(evt);
            }
        });

        publisherButton.setBackground(new java.awt.Color(204, 204, 204));
        publisherButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-new-2.png"))); // NOI18N
        publisherButton.setText("New- F4");
        publisherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherButtonActionPerformed(evt);
            }
        });

        authorButton.setBackground(new java.awt.Color(204, 204, 204));
        authorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-new-2.png"))); // NOI18N
        authorButton.setText("New - F3");
        authorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Book Id");

        bookIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdTextActionPerformed(evt);
            }
        });
        bookIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bookIdTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(languageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(languageCombo, 0, 156, Short.MAX_VALUE)
                            .addComponent(categoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryButton)
                            .addComponent(languageButton))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(publisherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(publisherCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(publisherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(authorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorButton))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bookIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryButton)
                    .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorButton))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(languageCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(languageLabel)
                            .addComponent(languageButton)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherLabel)
                            .addComponent(publisherCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherButton))))
                .addGap(17, 17, 17))
        );

        supplierLabel.setText("Spplier Name");

        supCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supComboActionPerformed(evt);
            }
        });
        supCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supComboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supComboKeyReleased(evt);
            }
        });

        costLabel.setText("Cost Price");

        salesLabel.setText("Sales Price");

        costText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTextActionPerformed(evt);
            }
        });
        costText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costTextKeyReleased(evt);
            }
        });

        salesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesTextActionPerformed(evt);
            }
        });
        salesText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salesTextKeyReleased(evt);
            }
        });

        qtyLabel.setText("QtyOnHand");

        reOrderLabel.setText("Re Order Level");

        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });
        qtyText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyTextKeyReleased(evt);
            }
        });

        reOrderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reOrderTextActionPerformed(evt);
            }
        });
        reOrderText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reOrderTextKeyReleased(evt);
            }
        });

        discountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTextActionPerformed(evt);
            }
        });
        discountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountTextKeyReleased(evt);
            }
        });

        jLabel5.setText("Discount");

        supplierButton.setBackground(new java.awt.Color(204, 204, 204));
        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-new-2.png"))); // NOI18N
        supplierButton.setText("New - F5");
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(costLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(supplierLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                    .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(supCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplierButton)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(reOrderLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(reOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salesText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(227, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemLabel)
                    .addComponent(itemText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierButton)
                    .addComponent(supplierLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costLabel)
                        .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salesLabel)
                        .addComponent(salesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reOrderLabel)
                    .addComponent(reOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyLabel))
                .addGap(4, 4, 4))
        );

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-add.png"))); // NOI18N
        registerButton.setText("Register");
        registerButton.setToolTipText("Click to Register Item");
        registerButton.setEnabled(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Item Registration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(registerButton)
                        .addGap(50, 50, 50)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextActionPerformed
        
    }//GEN-LAST:event_itemTextActionPerformed

    private void itemTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTextKeyReleased
    }//GEN-LAST:event_itemTextKeyReleased

    private void descriptionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextActionPerformed
        discountText.requestFocus();
    }//GEN-LAST:event_descriptionTextActionPerformed

    private void descriptionTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionTextKeyReleased

        String text = descriptionText.getText().toUpperCase();
        if (text.equals("BOOK")) {
            String nextId1;
            try {
                nextId1 = IdGenerator.getNextId("Book", "bookId", "B");
                bookIdText.setText(nextId1);
                bookIdText.setEnabled(true);
                titleText.setEnabled(true);
                titleText.setBackground(Color.WHITE);
                bookIdText.setBackground(Color.WHITE);
                languageCombo.setEnabled(true);
                authorCombo.setEnabled(true);
                categoryCombo.setEnabled(true);
                publisherCombo.setEnabled(true);
                jPanel3.setBackground(Color.WHITE);
                categoryButton.setEnabled(true);
                authorButton.setEnabled(true);
                languageButton.setEnabled(true);
                publisherButton.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            bookIdText.setEnabled(false);
            titleText.setEnabled(false);
            titleText.setText("");
            titleText.setBackground(Color.LIGHT_GRAY);
            bookIdText.setText("");
            bookIdText.setBackground(Color.LIGHT_GRAY);
            languageCombo.setEnabled(false);
            authorCombo.setEnabled(false);
            categoryCombo.setEnabled(false);
            publisherCombo.setEnabled(false);
            categoryButton.setEnabled(false);
            authorButton.setEnabled(false);
            languageButton.setEnabled(false);
            publisherButton.setEnabled(false);
            jPanel3.setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_descriptionTextKeyReleased

    private void titleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextActionPerformed

        categoryCombo.requestFocus();
        categoryCombo.showPopup();
    }//GEN-LAST:event_titleTextActionPerformed

    private void titleTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTextKeyReleased
        check();
    }//GEN-LAST:event_titleTextKeyReleased

    private void categoryComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboActionPerformed
    }//GEN-LAST:event_categoryComboActionPerformed

    private void categoryComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            authorCombo.requestFocus();
            authorCombo.showPopup();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            categoryButton.doClick();
        }
    }//GEN-LAST:event_categoryComboKeyPressed

    private void categoryComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            categoryButton.setEnabled(true);
        }
    }//GEN-LAST:event_categoryComboKeyReleased

    private void languageComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboActionPerformed
    }//GEN-LAST:event_languageComboActionPerformed

    private void languageComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_languageComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            publisherCombo.requestFocus();
            publisherCombo.showPopup();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            languageButton.doClick();
        }
    }//GEN-LAST:event_languageComboKeyPressed

    private void languageComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_languageComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            languageButton.setEnabled(true);
        }
    }//GEN-LAST:event_languageComboKeyReleased

    private void authorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorComboActionPerformed
    }//GEN-LAST:event_authorComboActionPerformed

    private void authorComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            languageCombo.requestFocus();
            languageCombo.showPopup();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            authorButton.doClick();
        }
    }//GEN-LAST:event_authorComboKeyPressed

    private void authorComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            authorButton.setEnabled(true);
        }
    }//GEN-LAST:event_authorComboKeyReleased

    private void publisherComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherComboActionPerformed
    }//GEN-LAST:event_publisherComboActionPerformed

    private void publisherComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            supCombo.requestFocus();
            supCombo.showPopup();
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            publisherButton.doClick();
        }
    }//GEN-LAST:event_publisherComboKeyPressed

    private void publisherComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            publisherButton.setEnabled(true);
        }
    }//GEN-LAST:event_publisherComboKeyReleased

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        AddCategoryForm frame = new AddCategoryForm();
        frame.setVisible(true);
        JDialog categoryDialog = new JDialog();
        categoryDialog.setSize(700, 450);
        categoryDialog.setLocationRelativeTo(null);
        categoryDialog.setContentPane(frame);
        categoryDialog.setVisible(true);
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void categoryButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoryButtonKeyReleased
    }//GEN-LAST:event_categoryButtonKeyReleased

    private void languageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageButtonActionPerformed
        AddLanguageForm frame = new AddLanguageForm();
        frame.setVisible(true);
        JDialog languageDialog = new JDialog();
        languageDialog.setSize(610, 450);
        languageDialog.setLocationRelativeTo(null);
        languageDialog.setContentPane(frame);
        languageDialog.setVisible(true);
    }//GEN-LAST:event_languageButtonActionPerformed

    private void publisherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherButtonActionPerformed
        AddPublisherForm frame = new AddPublisherForm();
        frame.setVisible(true);
        JDialog publisherDialog = new JDialog();
        publisherDialog.setSize(590, 420);
        publisherDialog.setLocationRelativeTo(null);
        publisherDialog.setContentPane(frame);
        publisherDialog.setVisible(true);

    }//GEN-LAST:event_publisherButtonActionPerformed

    private void authorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorButtonActionPerformed
        AddAuthorForm frame = new AddAuthorForm();
        frame.setVisible(true);
        frame.nameText.requestFocus();
        JDialog authorDialog = new JDialog();
        authorDialog.setSize(590, 420);
        authorDialog.setLocationRelativeTo(null);
        authorDialog.setContentPane(frame);
        authorDialog.setVisible(true);
    }//GEN-LAST:event_authorButtonActionPerformed

    private void bookIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdTextActionPerformed

        titleText.requestFocus();
    }//GEN-LAST:event_bookIdTextActionPerformed

    private void bookIdTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookIdTextKeyReleased
        check();
    }//GEN-LAST:event_bookIdTextKeyReleased

    private void supComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supComboActionPerformed
    }//GEN-LAST:event_supComboActionPerformed

    private void supComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supComboKeyPressed
        costText.requestFocus();
    }//GEN-LAST:event_supComboKeyPressed

    private void supComboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supComboKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            supplierButton.setEnabled(true);
        }
    }//GEN-LAST:event_supComboKeyReleased

    private void costTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTextActionPerformed
        qtyText.requestFocus();
    }//GEN-LAST:event_costTextActionPerformed

    private void costTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costTextKeyReleased
        check();
    }//GEN-LAST:event_costTextKeyReleased

    private void salesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesTextActionPerformed
        reOrderText.requestFocus();
    }//GEN-LAST:event_salesTextActionPerformed

    private void salesTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesTextKeyReleased
        check();
    }//GEN-LAST:event_salesTextKeyReleased

    private void reOrderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reOrderTextActionPerformed
        registerButton.setEnabled(true);
        registerButton.doClick();
    }//GEN-LAST:event_reOrderTextActionPerformed

    private void reOrderTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reOrderTextKeyReleased
        check();
    }//GEN-LAST:event_reOrderTextKeyReleased

    private void discountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTextActionPerformed
        String text = descriptionText.getText().toUpperCase();
        if (text.equals("BOOK")) {
            titleText.requestFocus();
        } else {
            supCombo.requestFocus();
            supCombo.showPopup();
        }
    }//GEN-LAST:event_discountTextActionPerformed

    private void discountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountTextKeyReleased
        check();
    }//GEN-LAST:event_discountTextKeyReleased

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        AddSupplierForm frame = new AddSupplierForm();
        frame.setVisible(true);
        JDialog supplierDialog = new JDialog();
        supplierDialog.setSize(750, 600);
        supplierDialog.setLocationRelativeTo(null);
        supplierDialog.setContentPane(frame);
        supplierDialog.setVisible(true);
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to add Item?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (response == 0) {
            String text = descriptionText.getText().toUpperCase();
            if (text.equals("BOOK")) {
                Category category = (Category) categoryCombo.getSelectedItem();
                Author author = (Author) authorCombo.getSelectedItem();
                Language language = (Language) languageCombo.getSelectedItem();
                Publisher publisher = (Publisher) publisherCombo.getSelectedItem();
                Supplier supplier = (Supplier) supCombo.getSelectedItem();
                Item item = new Item(itemText.getText(), descriptionText.getText(), Double.parseDouble(costText.getText()), Double.parseDouble(salesText.getText()), Double.parseDouble(discountText.getText()), Integer.parseInt(qtyText.getText()), Integer.parseInt(reOrderText.getText()), supplier.getSupplierId());
                Book book = new Book(titleText.getText(), publisher.getPublisherId(), author.getAuthorId(), language.getLangId(), bookIdText.getText(), itemText.getText(), category.getCategoryId());
                int res;
                int res1;
                try {
                    res = ItemController.addItem(item);
                    res1 = BookController.addBook(book);
                    if (res > 0 && res1 > 0) {
                        JOptionPane.showMessageDialog(null, "Item added successfully!");
                        String nextId = IdGenerator.getNextId("Item", "idItem", "I");
                        itemText.setText(nextId);
                        descriptionText.setText("");
                        discountText.setText("");
                        titleText.setText("");
                        salesText.setText("");
                        costText.setText("");
                        qtyText.setText("");
                        reOrderText.setText("");
                        bookIdText.setText("");
                        descriptionText.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to Add Item.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddItemForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Supplier supplier = (Supplier) supCombo.getSelectedItem();
                Item item = new Item(itemText.getText(), descriptionText.getText(), Double.parseDouble(costText.getText()), Double.parseDouble(salesText.getText()), Double.parseDouble(discountText.getText()), Integer.parseInt(qtyText.getText()), Integer.parseInt(reOrderText.getText()), supplier.getSupplierId());
                try {
                    int res = ItemController.addItem(item);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Item added successfully!");
                        String nextId = IdGenerator.getNextId("Item", "idItem", "I");
                        itemText.setText(nextId);
                        descriptionText.setText("");
                        discountText.setText("");
                        titleText.setText("");
                        salesText.setText("");
                        costText.setText("");
                        qtyText.setText("");
                        reOrderText.setText("");
                        bookIdText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to Add Item.");
                    }
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jPanel5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5KeyReleased

    private void qtyTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTextKeyReleased
        check();
    }//GEN-LAST:event_qtyTextKeyReleased

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        salesText.requestFocus();
    }//GEN-LAST:event_qtyTextActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorButton;
    private javax.swing.JComboBox authorCombo;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField bookIdText;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JButton categoryButton;
    private javax.swing.JComboBox categoryCombo;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField costText;
    private javax.swing.JLabel descriptionLabel;
    public javax.swing.JTextField descriptionText;
    private javax.swing.JTextField discountText;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JTextField itemText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton languageButton;
    private javax.swing.JComboBox languageCombo;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JButton publisherButton;
    private javax.swing.JComboBox publisherCombo;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyText;
    private javax.swing.JLabel reOrderLabel;
    private javax.swing.JTextField reOrderText;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JTextField salesText;
    private javax.swing.JComboBox supCombo;
    private javax.swing.JButton supplierButton;
    private javax.swing.JLabel supplierLabel;
    private javax.swing.JTextField titleText;
    // End of variables declaration//GEN-END:variables

    private void fillCategoryCombo() throws SQLException, ClassNotFoundException {
        List<Category> categoryList = CategoryController.getAllCategory();
        b = false;
        categoryCombo.removeAllItems();
        for (Category category : categoryList) {
            categoryCombo.addItem(category);
        }
        b = true;
    }

    private void fillLanguageCombo() throws SQLException, ClassNotFoundException {
        List<Language> languageList = LanguageController.getAllLanguages();
        b = false;
        languageCombo.removeAllItems();
        for (Language language : languageList) {
            languageCombo.addItem(language);
        }
        b = true;
    }

    private void fillAuthorCombo() throws ClassNotFoundException, SQLException {
        List<Author> authorList = AuthorController.getAllAuthors();
        b = false;
        authorCombo.removeAllItems();
        for (Author author : authorList) {
            authorCombo.addItem(author);
        }
        b = true;
    }

    private void fillPublisherCombo() throws SQLException, ClassNotFoundException {
        List<Publisher> publisherList = publisherController.getAllPublishers();
        b = false;
        publisherCombo.removeAllItems();
        for (Publisher publisher : publisherList) {
            publisherCombo.addItem(publisher);
        }
        b = true;
    }

    private void fillSupplierCombo() throws SQLException, ClassNotFoundException {
        List<Supplier> supplierList = SupplierController.getAllSuppliers();
        b = false;
        supCombo.removeAllItems();
        for (Supplier supplier : supplierList) {
            supCombo.addItem(supplier);
        }
        b = true;
    }

    public void check() {
        String desName = descriptionText.getText().toUpperCase();
        if (!desName.equals("BOOK")) {
            boolean b = discountText.getText().isEmpty() || costText.getText().isEmpty() || salesText.getText().isEmpty() || reOrderText.getText().isEmpty() || qtyText.getText().isEmpty();
            if (b == false) {
                registerButton.setEnabled(true);
            } else {
                registerButton.setEnabled(false);
            }
        } else {
            boolean b = discountText.getText().isEmpty() || costText.getText().isEmpty() || salesText.getText().isEmpty() || reOrderText.getText().isEmpty() || qtyText.getText().isEmpty() || bookIdText.getText().isEmpty() || titleText.getText().isEmpty();
            if (b == false) {
                registerButton.setEnabled(true);
            } else {
                registerButton.setEnabled(false);
            }
        }
    }
}
