/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ljse.cmjd31.inventorycontrolsystem.view.item;

import com.ijse.cmjd31.inventorycontrolsystem.controller.AuthorController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.BookController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.CategoryController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.ItemController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.LanguageController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.SupplierController;
import com.ijse.cmjd31.inventorycontrolsystem.controller.publisherController;
import com.ijse.cmjd31.inventorycontrolsystem.model.Book;
import com.ijse.cmjd31.inventorycontrolsystem.model.Book_Item;
import com.ijse.cmjd31.inventorycontrolsystem.model.Item;
import com.ijse.cmjd31.inventorycontrolsystem.model.Supplier;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1
 */
public class SearchItemForm extends javax.swing.JPanel {

    /**
     * Creates new form ItemSearch
     */
    private boolean b;

    public SearchItemForm() {
        initComponents();
        try {
            filBook_IdCombo();
        } catch (SQLException ex) {
            Logger.getLogger(SearchItemForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        reOrderText = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        descriptionText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        languageText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        categoryText = new javax.swing.JTextField();
        publisherText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        costText = new javax.swing.JTextField();
        salesText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        supplierText = new javax.swing.JTextField();
        qtyText = new javax.swing.JTextField();
        reorderText = new javax.swing.JTextField();
        idCombo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        discountText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mail-find.png"))); // NOI18N
        searchButton.setText("Serach Item");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        reOrderText.setBackground(new java.awt.Color(255, 255, 255));
        reOrderText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Details", 0, 0, null, new java.awt.Color(0, 51, 102)));

        jLabel5.setText("Item Detail");

        descriptionText.setEditable(false);
        descriptionText.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Description");

        bookPanel.setBackground(new java.awt.Color(255, 255, 255));
        bookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Book Detail", 0, 0, null, new java.awt.Color(0, 51, 102)));

        jLabel8.setText("Category");

        jLabel9.setText("Author");

        jLabel10.setText("Language");

        jLabel11.setText("Publisher");

        languageText.setEditable(false);
        languageText.setBackground(new java.awt.Color(255, 255, 255));

        authorText.setEditable(false);
        authorText.setBackground(new java.awt.Color(255, 255, 255));

        categoryText.setEditable(false);
        categoryText.setBackground(new java.awt.Color(255, 255, 255));
        categoryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTextActionPerformed(evt);
            }
        });

        publisherText.setEditable(false);
        publisherText.setBackground(new java.awt.Color(255, 255, 255));
        publisherText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addComponent(languageText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bookPanelLayout.createSequentialGroup()
                            .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(publisherText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bookPanelLayout.createSequentialGroup()
                            .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(categoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(languageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(23, 23, 23))
        );

        jLabel12.setText("Spplier Name");

        jLabel13.setText("Cost Price");

        jLabel14.setText("Sales Price");

        costText.setEditable(false);
        costText.setBackground(new java.awt.Color(255, 255, 255));

        salesText.setEditable(false);
        salesText.setBackground(new java.awt.Color(255, 255, 255));
        salesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesTextActionPerformed(evt);
            }
        });

        jLabel15.setText("QtyOnHand");

        jLabel16.setText("Re Order Qty");

        supplierText.setEditable(false);
        supplierText.setBackground(new java.awt.Color(255, 255, 255));

        qtyText.setEditable(false);
        qtyText.setBackground(new java.awt.Color(255, 255, 255));
        qtyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextActionPerformed(evt);
            }
        });

        reorderText.setEditable(false);
        reorderText.setBackground(new java.awt.Color(255, 255, 255));

        idCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });

        jLabel17.setText("Discount");

        javax.swing.GroupLayout reOrderTextLayout = new javax.swing.GroupLayout(reOrderText);
        reOrderText.setLayout(reOrderTextLayout);
        reOrderTextLayout.setHorizontalGroup(
            reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reOrderTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reOrderTextLayout.createSequentialGroup()
                        .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(reOrderTextLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180))
                    .addGroup(reOrderTextLayout.createSequentialGroup()
                        .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reOrderTextLayout.createSequentialGroup()
                                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(reOrderTextLayout.createSequentialGroup()
                                        .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(costText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(supplierText)))
                                    .addGroup(reOrderTextLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qtyText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                                .addGap(29, 29, 29)
                                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salesText, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(reorderText)))
                            .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        reOrderTextLayout.setVerticalGroup(
            reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reOrderTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(descriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(discountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(supplierText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(costText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(15, 15, 15)
                .addGroup(reOrderTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(reorderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(qtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Item Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(reOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchButton)
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reOrderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed

        try {
            if (b) {
                Object ob = idCombo.getSelectedItem();
                if (ob instanceof Item) {
                    bookPanel.setEnabled(false);
                    Item item = (Item) idCombo.getSelectedItem();
                    String supplierId = ItemController.getSupplierById(item.getItemCode());
                    Supplier supplier = SupplierController.getSupplierByItemCode(supplierId);
                    supplierText.setText(supplier.getSupplierName());
                    descriptionText.setText(item.getDescription());
                    discountText.setText(Double.toString(item.getDiscount()));
                    salesText.setText(Double.toString(item.getSalesPrice()));
                    costText.setText(Double.toString(item.getCostPrice()));
                    reorderText.setText(Integer.toString(item.getReOrderLevel()));
                    qtyText.setText(Integer.toString(item.getQtyOnHand()));
                } else if (ob instanceof Book_Item) {
                    Book_Item bookItem = (Book_Item) idCombo.getSelectedItem();
                    bookPanel.setEnabled(true);
                    String supplierId = ItemController.getSupplierById(bookItem.getItemCode());
                    Supplier supplier = SupplierController.getSupplierByItemCode(supplierId);
                    supplierText.setText(supplier.getSupplierName());
                    String category = CategoryController.getCategoryName(bookItem.getCategoryId());
                    categoryText.setText(category);
                    String publisher = publisherController.getPublisherName(bookItem.getPublisherId());
                    publisherText.setText(publisher);
                    String author = AuthorController.getAuthorName(bookItem.getAuthorId());
                    authorText.setText(author);
                    String language = LanguageController.getLanguageName(bookItem.getLanguageId());
                    System.out.println(language);
                    languageText.setText(language);
                    Item item = ItemController.getItemByItemCode(bookItem.getItemCode());
                    descriptionText.setText(item.getDescription());
                    discountText.setText(Double.toString(item.getDiscount()));
                    salesText.setText(Double.toString(item.getSalesPrice()));
                    costText.setText(Double.toString(item.getCostPrice()));
                    reorderText.setText(Integer.toString(item.getReOrderLevel()));
                    qtyText.setText(Integer.toString(item.getQtyOnHand()));
                }
            }
        } catch (SQLException sQLException) {
        } catch (ClassNotFoundException classNotFoundException) {
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void categoryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTextActionPerformed

    private void publisherTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherTextActionPerformed

    private void salesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesTextActionPerformed

    private void qtyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTextActionPerformed

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        try {
            if (b) {
                Object ob = idCombo.getSelectedItem();
                if (ob instanceof Item) {
                    bookPanel.setEnabled(false);
                    Item item = (Item) idCombo.getSelectedItem();
                    String supplierId = ItemController.getSupplierById(item.getItemCode());
                    Supplier supplier = SupplierController.getSupplierByItemCode(supplierId);
                    supplierText.setText(supplier.getSupplierName());
                    descriptionText.setText(item.getDescription());
                    discountText.setText(Double.toString(item.getDiscount()));
                    salesText.setText(Double.toString(item.getSalesPrice()));
                    costText.setText(Double.toString(item.getCostPrice()));
                    reorderText.setText(Integer.toString(item.getReOrderLevel()));
                    qtyText.setText(Integer.toString(item.getQtyOnHand()));
                } else if (ob instanceof Book_Item) {
                    Book_Item bookItem = (Book_Item) idCombo.getSelectedItem();
                    bookPanel.setEnabled(true);
                    String supplierId = ItemController.getSupplierById(bookItem.getItemCode());
                    Supplier supplier = SupplierController.getSupplierByItemCode(supplierId);
                    supplierText.setText(supplier.getSupplierName());
                    String category = CategoryController.getCategoryName(bookItem.getCategoryId());
                    categoryText.setText(category);
                    String publisher = publisherController.getPublisherName(bookItem.getPublisherId());
                    publisherText.setText(publisher);
                    String author = AuthorController.getAuthorName(bookItem.getAuthorId());
                    authorText.setText(author);
                    String language = LanguageController.getLanguageName(bookItem.getLanguageId());
                    System.out.println(language);
                    languageText.setText(language);
                    Item item = ItemController.getItemByItemCode(bookItem.getItemCode());
                    descriptionText.setText(item.getDescription());
                    discountText.setText(Double.toString(item.getDiscount()));
                    salesText.setText(Double.toString(item.getSalesPrice()));
                    costText.setText(Double.toString(item.getCostPrice()));
                    reorderText.setText(Integer.toString(item.getReOrderLevel()));
                    qtyText.setText(Integer.toString(item.getQtyOnHand()));
                }
            }
        } catch (SQLException sQLException) {
        } catch (ClassNotFoundException classNotFoundException) {
        }
    }//GEN-LAST:event_idComboActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorText;
    private javax.swing.JPanel bookPanel;
    private javax.swing.JTextField categoryText;
    private javax.swing.JTextField costText;
    private javax.swing.JTextField descriptionText;
    private javax.swing.JTextField discountText;
    private javax.swing.JComboBox idCombo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField languageText;
    private javax.swing.JTextField publisherText;
    private javax.swing.JTextField qtyText;
    private javax.swing.JPanel reOrderText;
    private javax.swing.JTextField reorderText;
    private javax.swing.JTextField salesText;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField supplierText;
    // End of variables declaration//GEN-END:variables

    private void filBook_IdCombo() throws SQLException, ClassNotFoundException {
        List<Book_Item> itemBookList = BookController.getAllItems();
        List<Item> itemList = ItemController.getAllItemsNotBooks();
        b = false;
        idCombo.removeAllItems();
        for (Book_Item bookList : itemBookList) {
            idCombo.addItem(bookList);
        }
        for (Item item : itemList) {
            idCombo.addItem(item);
        }
        b = true;
    }
}
