/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.cmjd31.inventorycontrolsystem.view.login;

import com.ijse.cmjd31.inventorycontrolsystem.controller.UserController;
import com.ijse.cmjd31.inventorycontrolsystem.main.HomePanel;
import com.ijse.cmjd31.inventorycontrolsystem.main.MainFrame;
import com.ijse.cmjd31.inventorycontrolsystem.model.User;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author 1
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    Timer timer;

    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
        nameField.requestFocus();
        animatedLabel.setVisible(false);
        quoteLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        logPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        animatedLabel = new javax.swing.JLabel();
        quoteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sa.jpg"))); // NOI18N
        imageLabel.setText("jLabel1");
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 128, 96));

        logLabel.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        logLabel.setForeground(new java.awt.Color(255, 255, 255));
        logLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logLabel.setText("Login");
        jPanel1.add(logLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 31, 257, -1));

        nameLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("User Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 118, 166, -1));

        passwordLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 164, 166, -1));

        nameField.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 118, 251, 28));

        passwordField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 166, 251, 28));

        logPanel.setBackground(new java.awt.Color(0, 102, 153));

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log In");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(logPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 120, 30));

        animatedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/graphics-books-453003.gif"))); // NOI18N
        animatedLabel.setText("jLabel7");
        jPanel1.add(animatedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 60));

        quoteLabel.setBackground(new java.awt.Color(51, 51, 0));
        quoteLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a.jpg"))); // NOI18N
        quoteLabel.setText("jLabel1");
        jPanel1.add(quoteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 520, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        passwordField.requestFocus();
    }//GEN-LAST:event_nameFieldActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        String name = nameField.getText();
        String password = new String(passwordField.getPassword());
        User user;
        try {
            user = UserController.getUser(name, password);
            if (user == null) {
                JOptionPane.showMessageDialog(null, "Invalid UserName Or Password");
            } else {
                int priviledge = user.getPrivilege();
                if (priviledge == 1) {
                    imageLabel.setVisible(false);
                    quoteLabel.setVisible(true);
                    nameLabel.setVisible(false);
                    passwordLabel.setVisible(false);
                    nameField.setVisible(false);
                    passwordField.setVisible(false);
                    logPanel.setVisible(false);
                    logLabel.setVisible(false);
                    animatedLabel.setVisible(true);
                    jPanel1.setBackground(new Color(0, 0, 0));
                    timer = new Timer(3500, new ActionListener() {
                        boolean b = false;

                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (!b) {
                                dispose();
                                new MainFrame(false).setVisible(true);
                                b = true;
                                timer.stop();
                            }
                        }
                    });
                    timer.start();
                } else if (priviledge == 2) {
                    imageLabel.setVisible(false);
                    quoteLabel.setVisible(true);
                    nameLabel.setVisible(false);
                    passwordLabel.setVisible(false);
                    nameField.setVisible(false);
                    passwordField.setVisible(false);
                    logPanel.setVisible(false);
                    logLabel.setVisible(false);
                    animatedLabel.setVisible(true);
                    jPanel1.setBackground(new Color(0, 0, 0));
                    timer = new Timer(3500, new ActionListener() {
                        boolean b = false;

                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if (!b) {
                                dispose();
                                MainFrame frame = new MainFrame(true);
                                frame.setVisible(true);
                                b = true;
                                timer.stop();
                            }
                        }
                    });
                    timer.start();
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        jLabel5.requestFocus();
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel animatedLabel;
    public javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel logLabel;
    public javax.swing.JPanel logPanel;
    public javax.swing.JTextField nameField;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JPasswordField passwordField;
    public javax.swing.JLabel passwordLabel;
    public javax.swing.JLabel quoteLabel;
    // End of variables declaration//GEN-END:variables
}
