/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.cmjd31.inventorycontrolsystem.main;

import com.ijse.cmjd31.inventorycontrolsystem.view.login.LogOutForm;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author 1
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form BookForm
     */
    SimpleDateFormat simpleDateFormat;
    Timer timer;
    Date date;
    DateFormat instanceTime;

    public HomePanel() {
        initComponents();
        simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = simpleDateFormat.format(new Date());
        // dateLabel.setText(formattedDate);
        instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                date = new Date();
                String format = instanceTime.format(date);
                clockLabel.setText(format);
            }
        });
        timer.start();
    }
    
     public HomePanel(boolean privilege) {
        initComponents();
        simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = simpleDateFormat.format(new Date());
        // dateLabel.setText(formattedDate);
        instanceTime = DateFormat.getTimeInstance(SimpleDateFormat.MEDIUM);
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                date = new Date();
                String format = instanceTime.format(date);
                clockLabel.setText(format);
            }
        });
        timer.start();
        userPanel.setVisible(false);
        userPanel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        clockLabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        clockLabel.setForeground(new java.awt.Color(0, 51, 102));
        clockLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(clockLabel);
        clockLabel.setBounds(0, 620, 230, 40);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Log Out");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        add(jPanel4);
        jPanel4.setBounds(1020, 590, 130, 40);

        userPanel.setBackground(new java.awt.Color(0, 51, 102));

        userLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("User Profile");
        userLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(userPanel);
        userPanel.setBounds(1020, 540, 130, 40);

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/large-wall-bookshelf.jpg"))); // NOI18N
        label.setText("jLabel10");
        add(label);
        label.setBounds(90, 0, 1080, 680);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/large-wall-bookshelf.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 90, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed

        LogOutForm frame = new LogOutForm();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setBounds(570, 300, 550, 220);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setFont(new Font("Andalus", 4, 22));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setFont(new Font("Andalus", 4, 18));
    }//GEN-LAST:event_jLabel4MouseExited

    private void userLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMousePressed
        UserProfileForm form = new UserProfileForm(null, true);
        form.setVisible(true);
    }//GEN-LAST:event_userLabelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clockLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JLabel label;
    public javax.swing.JLabel userLabel;
    public javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
