/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.cmjd31.inventorycontrolsystem.main;

import com.ijse.cmjd31.inventorycontrolsystem.controller.BackUp;
import com.ijse.cmjd31.inventorycontrolsystem.other.ChangeColor;
import com.ijse.cmjd31.inventorycontrolsystem.view.customer.CustomerManageForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.book.BookForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.item.ItemForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.CustomerOrderForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.EditPurchaseOrderForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.InvoicePaymentForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.NewPurchaseOrderForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.ReportForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.ReturnPurchaseOrderForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.order.UpdateInvoiceForm;
import com.ljse.cmjd31.inventorycontrolsystem.view.supplier.SupplierManageForm;
import java.awt.Color;
import java.awt.Font;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    HomePanel homeFrame;
 
    boolean userPrivilege;

    public MainFrame(boolean userPrivilege) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.userPrivilege = userPrivilege;
        Thread thread = new Thread() {
            public void run() {
                while (true) {
                    try {
                        Properties prop = new Properties();
                        prop.load(new FileReader("appconfig.properties"));
                        String path = prop.getProperty("backupPath");
                        boolean res = BackUp.newBackupDB(path);
                        Thread.sleep(60000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

        thread.start();


//        dPane = new JDesktopPane() {
//            @Override
//            protected void paintComponent(Graphics g) {
//                Graphics2D gd = (Graphics2D) g;
        // Image image = Toolkit.getDefaultToolkit().getImage("./src/image/j.jpg");
        //Image img = Toolkit.getDefaultToolkit().getImage("./src/image/j.jpg");
        // Image img1 = Toolkit.getDefaultToolkit().getImage( "./src/image/l.jpg");
//              Image img2 = Toolkit.getDefaultToolkit().getImage( "./src/image/z6.jpg");
        // gd.drawImage(image, 0, 0, this);
        // gd.drawImage(img, 500, 0, this);
        // gd.drawImage(img1, 700, 0, this);
//                gd.drawImage(img2, 1100, 10, this);

//                setBackground(Color.WHITE);
//            }
//        };      
       if (userPrivilege) {
           homeFrame=new HomePanel();
            dPane1.removeAll();
            dPane1.repaint();
            dPane1.add(homeFrame);
            homeFrame.setVisible(true);
            homePanel.setBackground(new Color(153, 153, 255));
            homeFrame.setVisible(true);
            homeFrame.userPanel.setVisible(false);
            homeFrame.userLabel.setVisible(false);
          homeFrame.userLabel.setEnabled(false);
            reportLabel.setEnabled(false);
            reportLabel.setVisible(false);
            reportPanel.setBackground(new Color(0, 102, 153));
            homeFrame.setBounds(0, 0, 1220, 800);
        } else {
           homeFrame = new HomePanel();
            dPane1.removeAll();
            dPane1.repaint();
            dPane1.add(homeFrame);
            homePanel.setBackground(new Color(153, 153, 255));
            homeFrame.setVisible(true);
            homeFrame.setBounds(0, 0, 1220, 800);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        invoicePanel = new javax.swing.JPanel();
        invoiceLabel = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        updateLabel = new javax.swing.JLabel();
        newPurchasePanel = new javax.swing.JPanel();
        newPurchaseLabel = new javax.swing.JLabel();
        editPurchasePanel = new javax.swing.JPanel();
        editPurchaseLabel = new javax.swing.JLabel();
        returnPanel = new javax.swing.JPanel();
        returnLabel = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        supplierPanel = new javax.swing.JPanel();
        supplierLabel = new javax.swing.JLabel();
        itemPanel = new javax.swing.JPanel();
        itemLabel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        bookLabel = new javax.swing.JLabel();
        pane = new javax.swing.JPanel();
        dPane1 = new javax.swing.JDesktopPane();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setUndecorated(true);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 2));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Sadeepa Book Shop");

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Tel - 034 - 3741751 email - sadeepa@gmail.com");

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("No 50,Panadura Road,Horana");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sa.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(549, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(395, 395, 395))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1480, 110);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        invoicePanel.setBackground(new java.awt.Color(0, 102, 153));
        invoicePanel.setLayout(null);

        invoiceLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        invoiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        invoiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoiceLabel.setText("New Invoice");
        invoiceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invoiceLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invoiceLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invoiceLabelMousePressed(evt);
            }
        });
        invoicePanel.add(invoiceLabel);
        invoiceLabel.setBounds(14, 0, 160, 60);

        jPanel1.add(invoicePanel);
        invoicePanel.setBounds(0, 60, 200, 60);

        paymentPanel.setBackground(new java.awt.Color(0, 51, 102));

        paymentLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        paymentLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentLabel.setText("Invoice Payment");
        paymentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paymentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paymentLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paymentLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addComponent(paymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addComponent(paymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(paymentPanel);
        paymentPanel.setBounds(0, 120, 200, 70);

        updatePanel.setBackground(new java.awt.Color(0, 102, 153));

        updateLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateLabel.setText("Update Invoice");
        updateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(updateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        jPanel1.add(updatePanel);
        updatePanel.setBounds(0, 190, 200, 60);

        newPurchasePanel.setBackground(new java.awt.Color(0, 51, 102));

        newPurchaseLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        newPurchaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        newPurchaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newPurchaseLabel.setText("New Purchase Order");
        newPurchaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newPurchaseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newPurchaseLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newPurchaseLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout newPurchasePanelLayout = new javax.swing.GroupLayout(newPurchasePanel);
        newPurchasePanel.setLayout(newPurchasePanelLayout);
        newPurchasePanelLayout.setHorizontalGroup(
            newPurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPurchasePanelLayout.createSequentialGroup()
                .addComponent(newPurchaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        newPurchasePanelLayout.setVerticalGroup(
            newPurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newPurchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPurchaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        jPanel1.add(newPurchasePanel);
        newPurchasePanel.setBounds(0, 250, 200, 60);

        editPurchasePanel.setBackground(new java.awt.Color(0, 102, 153));

        editPurchaseLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        editPurchaseLabel.setForeground(new java.awt.Color(255, 255, 255));
        editPurchaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editPurchaseLabel.setText("Edit Purchase Order");
        editPurchaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editPurchaseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editPurchaseLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editPurchaseLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout editPurchasePanelLayout = new javax.swing.GroupLayout(editPurchasePanel);
        editPurchasePanel.setLayout(editPurchasePanelLayout);
        editPurchasePanelLayout.setHorizontalGroup(
            editPurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPurchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editPurchaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        editPurchasePanelLayout.setVerticalGroup(
            editPurchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPurchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editPurchaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(editPurchasePanel);
        editPurchasePanel.setBounds(0, 310, 200, 60);

        returnPanel.setBackground(new java.awt.Color(0, 51, 102));

        returnLabel.setBackground(new java.awt.Color(153, 153, 153));
        returnLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        returnLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnLabel.setText("Purchase Returns");
        returnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addComponent(returnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(returnPanel);
        returnPanel.setBounds(0, 370, 200, 60);

        customerPanel.setBackground(new java.awt.Color(0, 102, 153));

        customerLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerLabel.setText("Manage Customer");
        customerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(customerPanel);
        customerPanel.setBounds(0, 430, 200, 70);

        supplierPanel.setBackground(new java.awt.Color(0, 51, 102));

        supplierLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        supplierLabel.setForeground(new java.awt.Color(255, 255, 255));
        supplierLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierLabel.setText("Manage Supplier");
        supplierLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supplierLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout supplierPanelLayout = new javax.swing.GroupLayout(supplierPanel);
        supplierPanel.setLayout(supplierPanelLayout);
        supplierPanelLayout.setHorizontalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supplierPanelLayout.createSequentialGroup()
                .addComponent(supplierLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        supplierPanelLayout.setVerticalGroup(
            supplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supplierLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(supplierPanel);
        supplierPanel.setBounds(0, 500, 200, 70);

        itemPanel.setBackground(new java.awt.Color(0, 102, 153));

        itemLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        itemLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemLabel.setText("Manage Item");
        itemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout itemPanelLayout = new javax.swing.GroupLayout(itemPanel);
        itemPanel.setLayout(itemPanelLayout);
        itemPanelLayout.setHorizontalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemPanelLayout.createSequentialGroup()
                .addComponent(itemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        itemPanelLayout.setVerticalGroup(
            itemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(itemPanel);
        itemPanel.setBounds(0, 570, 200, 70);

        homePanel.setBackground(new java.awt.Color(0, 51, 102));

        homeLabel.setBackground(new java.awt.Color(0, 51, 102));
        homeLabel.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("Home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(homePanel);
        homePanel.setBounds(0, 0, 200, 60);

        reportPanel.setBackground(new java.awt.Color(0, 102, 153));

        reportLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        reportLabel.setForeground(new java.awt.Color(255, 255, 255));
        reportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportLabel.setText("View Reports");
        reportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reportLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addComponent(reportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        bookPanel.setBackground(new java.awt.Color(0, 51, 102));

        bookLabel.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        bookLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookLabel.setText("Manage Book");
        bookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addComponent(bookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        pane.setBackground(new java.awt.Color(255, 255, 255));
        pane.setLayout(new java.awt.BorderLayout());

        dPane1.setBackground(new java.awt.Color(255, 255, 255));
        pane.add(dPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(4399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        CustomerOrderForm frame = new CustomerOrderForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(invoicePanel);
    }//GEN-LAST:event_invoiceLabelMousePressed

    private void paymentLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        InvoicePaymentForm frame = new InvoicePaymentForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(paymentPanel);
    }//GEN-LAST:event_paymentLabelMousePressed

    private void updateLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        UpdateInvoiceForm frame = new UpdateInvoiceForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 780);
        sameColor();
        ChangeColor changeColor = new ChangeColor(updatePanel);
    }//GEN-LAST:event_updateLabelMousePressed

    private void newPurchaseLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPurchaseLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        NewPurchaseOrderForm frame = new NewPurchaseOrderForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1230, 580);
        sameColor();
        ChangeColor changeColor = new ChangeColor(newPurchasePanel);
    }//GEN-LAST:event_newPurchaseLabelMousePressed

    private void editPurchaseLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPurchaseLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        EditPurchaseOrderForm frame = new EditPurchaseOrderForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(editPurchasePanel);
    }//GEN-LAST:event_editPurchaseLabelMousePressed

    private void returnLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        ReturnPurchaseOrderForm frame;
        try {
            frame = new ReturnPurchaseOrderForm();
            dPane1.add(frame);
            frame.setVisible(true);
            frame.setBounds(0, 0, 1200, 590);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        sameColor();
        ChangeColor changeColor = new ChangeColor(returnPanel);
    }//GEN-LAST:event_returnLabelMousePressed

    private void invoiceLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLabelMouseEntered
        //panel1.setBackground(Color.BLACK);
        invoiceLabel.setFont(new Font("Andalus", 5, 25));
    }//GEN-LAST:event_invoiceLabelMouseEntered

    private void invoiceLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceLabelMouseExited
        invoiceLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_invoiceLabelMouseExited

    private void paymentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentLabelMouseEntered
        paymentLabel.setFont(new Font("Andalus", 5, 25));
    }//GEN-LAST:event_paymentLabelMouseEntered

    private void updateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLabelMouseEntered
        updateLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_updateLabelMouseEntered

    private void newPurchaseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPurchaseLabelMouseEntered
        newPurchaseLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_newPurchaseLabelMouseEntered

    private void editPurchaseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPurchaseLabelMouseEntered
        editPurchaseLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_editPurchaseLabelMouseEntered

    private void returnLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMouseEntered
        returnLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_returnLabelMouseEntered

    private void customerLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLabelMouseEntered
        customerLabel.setFont(new Font("Andalus", 5, 21));
    }//GEN-LAST:event_customerLabelMouseEntered

    private void supplierLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLabelMouseEntered
        supplierLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_supplierLabelMouseEntered

    private void bookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookLabelMouseEntered
        bookLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_bookLabelMouseEntered

    private void reportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseEntered
        reportLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_reportLabelMouseEntered

    private void paymentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentLabelMouseExited
        paymentLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_paymentLabelMouseExited

    private void updateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLabelMouseExited
        updateLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_updateLabelMouseExited

    private void newPurchaseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPurchaseLabelMouseExited
        newPurchaseLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_newPurchaseLabelMouseExited

    private void editPurchaseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPurchaseLabelMouseExited
        editPurchaseLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_editPurchaseLabelMouseExited

    private void returnLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMouseExited
        returnLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_returnLabelMouseExited

    private void customerLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLabelMouseExited
        customerLabel.setFont(new Font("Andalus", 5, 19));
    }//GEN-LAST:event_customerLabelMouseExited

    private void supplierLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLabelMouseExited
        supplierLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_supplierLabelMouseExited

    private void bookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookLabelMouseExited
        bookLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_bookLabelMouseExited

    private void reportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseExited
        reportLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_reportLabelMouseExited

    private void reportLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        ReportForm frame = new ReportForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 530);
        sameColor();
        ChangeColor changeColor = new ChangeColor(reportPanel);
    }//GEN-LAST:event_reportLabelMousePressed

    private void customerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        CustomerManageForm frame = new CustomerManageForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(customerPanel);
    }//GEN-LAST:event_customerLabelMousePressed

    private void bookLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        BookForm frame = new BookForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(bookPanel);
    }//GEN-LAST:event_bookLabelMousePressed

    private void bookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookLabelMouseClicked
    }//GEN-LAST:event_bookLabelMouseClicked

    private void supplierLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        SupplierManageForm frame = new SupplierManageForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(supplierPanel);
    }//GEN-LAST:event_supplierLabelMousePressed

    private void itemLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        ItemForm frame = new ItemForm();
        dPane1.add(frame);
        frame.setVisible(true);
        frame.setBounds(0, 0, 1220, 800);
        sameColor();
        ChangeColor changeColor = new ChangeColor(itemPanel);
    }//GEN-LAST:event_itemLabelMousePressed

    private void itemLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLabelMouseEntered
        itemLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_itemLabelMouseEntered

    private void itemLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLabelMouseExited
        itemLabel.setFont(new Font("Andalus", 5, 18));
    }//GEN-LAST:event_itemLabelMouseExited

    private void homeLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMousePressed
        dPane1.removeAll();
        dPane1.repaint();
        if (userPrivilege) {
           HomePanel panel= new HomePanel();
            dPane1.add(panel);
            panel.setVisible(true);
            panel.setBounds(0, 0, 1220, 800);
            sameColor();
            //ChangeColor changeColor = new ChangeColor(homePanel);
        } else {
            HomePanel frame = new HomePanel();
            dPane1.add(frame);
            frame.setVisible(true);
            frame.setBounds(0, 0, 1220, 800);
            sameColor();
            //ChangeColor changeColor = new ChangeColor(homePanel);
        }

    }//GEN-LAST:event_homeLabelMousePressed

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        homeLabel.setFont(new Font("Andalus", 5, 20));
    }//GEN-LAST:event_homeLabelMouseExited

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseEntered
        homeLabel.setFont(new Font("Andalus", 5, 22));
    }//GEN-LAST:event_homeLabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame(true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookLabel;
    public javax.swing.JPanel bookPanel;
    private javax.swing.JLabel customerLabel;
    public javax.swing.JPanel customerPanel;
    public javax.swing.JDesktopPane dPane1;
    private javax.swing.JLabel editPurchaseLabel;
    public javax.swing.JPanel editPurchasePanel;
    private javax.swing.JLabel homeLabel;
    public javax.swing.JPanel homePanel;
    private javax.swing.JLabel invoiceLabel;
    public javax.swing.JPanel invoicePanel;
    private javax.swing.JLabel itemLabel;
    public javax.swing.JPanel itemPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel newPurchaseLabel;
    public javax.swing.JPanel newPurchasePanel;
    private javax.swing.JPanel pane;
    private javax.swing.JLabel paymentLabel;
    public javax.swing.JPanel paymentPanel;
    public javax.swing.JLabel reportLabel;
    public javax.swing.JPanel reportPanel;
    private javax.swing.JLabel returnLabel;
    public javax.swing.JPanel returnPanel;
    private javax.swing.JLabel supplierLabel;
    public javax.swing.JPanel supplierPanel;
    private javax.swing.JLabel updateLabel;
    public javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables

    public void sameColor() {
        invoicePanel.setBackground(new Color(0, 102, 153));
        updatePanel.setBackground(new Color(0, 102, 153));
        editPurchasePanel.setBackground(new Color(0, 102, 153));
        customerPanel.setBackground(new Color(0, 102, 153));
        itemPanel.setBackground(new Color(0, 102, 153));
        reportPanel.setBackground(new Color(0, 102, 153));
        homePanel.setBackground(new Color(0, 51, 102));
        paymentPanel.setBackground(new Color(0, 51, 102));
        newPurchasePanel.setBackground(new Color(0, 51, 102));
        returnPanel.setBackground(new Color(0, 51, 102));
        supplierPanel.setBackground(new Color(0, 51, 102));
        bookPanel.setBackground(new Color(0, 51, 102));
    }
}
