/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.cmjd31.inventorycontrolsyatem.view.reportform;

import com.ijse.cmjd31.inventorycontrolsystem.db.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author 1
 */
public class StockStatusForm extends javax.swing.JPanel {

    /**
     * Creates new form SalesReportForm
     */
    SimpleDateFormat sdf;

    public StockStatusForm() {
        initComponents();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        currentStockButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        reOrderButton = new javax.swing.JRadioButton();
        currentStockButton = new javax.swing.JRadioButton();

        jLabel5.setText("jLabel5");

        jTextField1.setText("jTextField1");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generate Stock Reports");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        reOrderButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(reOrderButton);
        reOrderButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reOrderButton.setText("Generate Item List Below ReOrder Level");
        reOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reOrderButtonActionPerformed(evt);
            }
        });
        reOrderButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reOrderButtonKeyReleased(evt);
            }
        });

        currentStockButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(currentStockButton);
        currentStockButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        currentStockButton.setText("Generate Current Stock Status Report");
        currentStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentStockButtonActionPerformed(evt);
            }
        });
        currentStockButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                currentStockButtonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reOrderButton)
                            .addComponent(currentStockButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(currentStockButton)
                .addGap(57, 57, 57)
                .addComponent(reOrderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reOrderButtonActionPerformed
    }//GEN-LAST:event_reOrderButtonActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed

        if (reOrderButton.isSelected()) {
            try {
                JasperReport jr = JasperCompileManager.compileReport("./jasperreport/ReOrderLevelReport.jrxml");
                JasperPrint jp;
                try {
                    jp = JasperFillManager.fillReport(jr, null, DBConnection.getInstance().getConnection());
                    JasperViewer.viewReport(jp, false);
                } catch (SQLException ex) {
                    Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (JRException ex) {
                Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (currentStockButton.isSelected()) {
            try {
                JasperReport jr = JasperCompileManager.compileReport("./jasperreport/CurrentStockStatusReport.jrxml");
                JasperPrint jp;
                try {
                    jp = JasperFillManager.fillReport(jr, null, DBConnection.getInstance().getConnection());
                    JasperViewer.viewReport(jp, false);
                } catch (SQLException ex) {
                    Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (JRException ex) {
                Logger.getLogger(StockStatusForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void currentStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentStockButtonActionPerformed
    }//GEN-LAST:event_currentStockButtonActionPerformed

    private void currentStockButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentStockButtonKeyReleased
        if (currentStockButton.isSelected()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                generateButton.requestFocus();
                generateButton.doClick();
            }
        }
    }//GEN-LAST:event_currentStockButtonKeyReleased

    private void reOrderButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reOrderButtonKeyReleased
        if (reOrderButton.isSelected()) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                generateButton.requestFocus();
                generateButton.doClick();
            }
        }
    }//GEN-LAST:event_reOrderButtonKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton currentStockButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JRadioButton reOrderButton;
    // End of variables declaration//GEN-END:variables
}
