/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ljse.cmjd31.inventorycontrolsystem.view.book;

import com.ijse.cmjd31.inventorycontrolsystem.controller.AuthorController;
import com.ijse.cmjd31.inventorycontrolsystem.model.Author;
import com.ijse.cmjd31.inventorycontrolsystem.other.IdGenerator;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1
 */
public class ManageAuthorForm extends javax.swing.JPanel {

    /**
     * Creates new form AuthorManage
     */
    private boolean b;
    private String nextId;

    public ManageAuthorForm() {
        initComponents();
        try {
            fillIdCombo();
            nextId = IdGenerator.getNextId("Author", "idAuthor", "A");
            idText.setText(nextId);
            nameText.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idCombo = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel.setText("Author Id");

        idCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setText("Author Name");

        idText.setEditable(false);
        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFocusGained(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Author", 0, 0, new java.awt.Font("Baskerville Old Face", 1, 18))); // NOI18N

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-delete-2.png"))); // NOI18N
        deleteButton.setText("Delete - F3");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-new-2.png"))); // NOI18N
        addButton.setText("Add New - F1");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update-product.png"))); // NOI18N
        updateButton.setText("Update - F2");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(deleteButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Author Form");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        check();
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            updateButton.setEnabled(true);
            updateButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_F3) {
            deleteButton.setEnabled(true);
            deleteButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            addButton.setEnabled(true);
            addButton.doClick();
        }
    }//GEN-LAST:event_nameTextKeyReleased

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if (b) {
            Author author = (Author) idCombo.getSelectedItem();
            idText.setEnabled(false);
            idText.setText(author.getAuthorId());
            nameText.requestFocus();
            nameText.setText(author.getAuthor_Name());
        }
    }//GEN-LAST:event_idComboActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        nameText.requestFocus();
        check();
    }//GEN-LAST:event_idTextActionPerformed

    private void idTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFocusGained
        check();
    }//GEN-LAST:event_idTextFocusGained

    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased
        check();
        check();
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            updateButton.setEnabled(true);
            updateButton.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            deleteButton.setEnabled(true);
            deleteButton.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            addButton.setEnabled(true);
            addButton.doClick();
        }
    }//GEN-LAST:event_idTextKeyReleased

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        idText.setText("");
        if (!nameText.getText().isEmpty()) {
            Author author1 = (Author) idCombo.getSelectedItem();
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete Author " + author1.getAuthor_Name() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                int res;
                try {
                    res = AuthorController.deleteAuthor(author1.getAuthorId());
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Deleted Successfully.");
                        idText.setEnabled(true);
                        idText.requestFocus();
                        nextId= IdGenerator.getNextId("Author", "idAuthor", "A");
                        idText.setText(nextId);
                        nameText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.setText("");
                nameText.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an Author from Author Box to delete.");
            idCombo.requestFocus();
            idText.requestFocus();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!(idText.getText().isEmpty() || nameText.getText().isEmpty())) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to add Author " + nameText.getText() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                Author author = new Author(idText.getText(), nameText.getText());
                try {
                    int res = AuthorController.addAuthor(author);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Author added successfully.");
                        idText.requestFocus();
                        nextId= IdGenerator.getNextId("Author", "idAuthor", "A");
                        idText.setText(nextId);
                        nameText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to add Author.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.setText("");
                nameText.setText("");
            }
        } else if (idText.getText().isEmpty() && nameText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields Are Empty.Please fill them to add new Category!");
            idText.requestFocus();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        idText.setText("");
        if (!(nameText.getText().isEmpty())) {
            Author author1 = (Author) idCombo.getSelectedItem();
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to update Author " + author1.getAuthor_Name() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                Author author = new Author(author1.getAuthorId(), nameText.getText());
                int res;
                try {
                    res = AuthorController.updateAuthor(author);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Updated Successfully.");
                        idText.requestFocus();
                        idText.setEnabled(true);
                        nextId= IdGenerator.getNextId("Author", "idAuthor", "A");
                        idText.setText(nextId);
                        nameText.setText("");
                        idText.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to Update.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageAuthorForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.requestFocus();
                idText.setText("");
                nameText.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an Author from Author Box to Update .");
            idCombo.requestFocus();
            idText.requestFocus();
        }
    }//GEN-LAST:event_updateButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox idCombo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void fillIdCombo() throws SQLException, ClassNotFoundException {
        List<Author> authorList = AuthorController.getAllAuthors();
        b = false;
        idCombo.removeAllItems();
        for (Author author : authorList) {
            idCombo.addItem(author);
        }
        b = true;
    }

    public void check() {
        boolean bool = idText.getText().isEmpty() || nameText.getText().isEmpty();
        if (bool != true) {
            addButton.setEnabled(true);
        } else {
            addButton.setEnabled(false);
        }
    }
}
