/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ljse.cmjd31.inventorycontrolsystem.view.book;

import com.ijse.cmjd31.inventorycontrolsystem.controller.LanguageController;
import com.ijse.cmjd31.inventorycontrolsystem.model.Language;
import com.ijse.cmjd31.inventorycontrolsystem.other.IdGenerator;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1
 */
public class ManageLanguageForm extends javax.swing.JPanel {

    /**
     * Creates new form LanguageManage
     */
    private boolean b;
    private String nextId;

    public ManageLanguageForm() {
        initComponents();
        try {
            try {
                fillIdCombo();
                nextId = IdGenerator.getNextId("Language", "idLanguage", "L");
                nameText.requestFocus();
                idText.setText(nextId);
            } catch (SQLException ex) {
                Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idCombo = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(685, 430));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setPreferredSize(new java.awt.Dimension(865, 430));

        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel.setText("Language Id");

        idCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel.setText("Language Name");

        idText.setEditable(false);
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Language", 0, 0, new java.awt.Font("Baskerville Old Face", 1, 18))); // NOI18N

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-delete-2.png"))); // NOI18N
        deleteButton.setText("Delete - F3");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder-new-7.png"))); // NOI18N
        addButton.setText("Add New - F1");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update-product.png"))); // NOI18N
        updateButton.setText("Update - F2");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(deleteButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Language Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(29, 29, 29)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased

        check();
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            updateButton.setEnabled(true);
            updateButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_F3) {
            deleteButton.setEnabled(true);
            deleteButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_F1) {
            check();
            addButton.setEnabled(true);
            addButton.doClick();
        }
    }//GEN-LAST:event_nameTextKeyReleased

    private void idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboActionPerformed
        if (b) {
            Language language = (Language) idCombo.getSelectedItem();
            idText.setEnabled(false);
            idText.setText(language.getLangId());
            nameText.requestFocus();
            nameText.setText(language.getLang_Name());
        }
    }//GEN-LAST:event_idComboActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        nameText.requestFocus();
    }//GEN-LAST:event_idTextActionPerformed

    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased

        check();
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            updateButton.setEnabled(true);
            updateButton.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            deleteButton.setEnabled(true);
            deleteButton.doClick();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            check();
            addButton.setEnabled(true);
            addButton.doClick();
        }
    }//GEN-LAST:event_idTextKeyReleased

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        idText.setText("");
        if (!nameText.getText().isEmpty()) {
            Language language1 = (Language) idCombo.getSelectedItem();
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete Language " + language1.getLang_Name() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                int res;
                try {
                    res = LanguageController.deleteLanguage(language1.getLangId());
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Deleted Successfully.");
                        idText.setEnabled(true);
                        idText.requestFocus();
                        nextId = IdGenerator.getNextId("Language", "idLanguage", "L");
                        idText.setText(nextId);
                        nameText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to delete.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.setText("");
                nameText.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an Language from Language Box to delete.");
            idCombo.requestFocus();
            idText.requestFocus();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!(idText.getText().isEmpty() || nameText.getText().isEmpty())) {
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to add Language " + nameText.getText() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                Language language = new Language(idText.getText(), nameText.getText());

                int res;
                try {
                    res = LanguageController.addLanguage(language);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Language added successfully.");
                        idText.requestFocus();
                        nextId = IdGenerator.getNextId("Language", "idLanguage", "L");
                        idText.setText(nextId);
                        nameText.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to add Language.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.setText("");
                nameText.setText("");
            }
        } else if (idText.getText().isEmpty() && nameText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields Are Empty.Please fill them to add new Category!");
            idText.requestFocus();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        idText.setText("");
        if (!(nameText.getText().isEmpty())) {
            Language language1 = (Language) idCombo.getSelectedItem();

            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to update Language " + language1.getLang_Name() + " ? ", "Confirm", JOptionPane.YES_NO_OPTION);
            if (response == 0) {
                Language language = new Language(language1.getLangId(), nameText.getText());
                int res;
                try {
                    res = LanguageController.updateLanguage(language);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Updated Successfully.");
                        idText.requestFocus();
                        idText.setEnabled(true);
                        nextId = IdGenerator.getNextId("Language", "idLanguage", "L");
                        idText.setText(nextId);
                        nameText.setText("");
                        idText.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to Update.");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageLanguageForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                idText.requestFocus();
                idText.setEnabled(true);
                idText.requestFocus();
                idText.setText("");
                nameText.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Language from Language Box to Update .");
            idCombo.requestFocus();
            idText.requestFocus();
        }
    }//GEN-LAST:event_updateButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox idCombo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void fillIdCombo() throws SQLException, ClassNotFoundException {
        List<Language> languageList = LanguageController.getAllLanguages();
        b = false;
        idCombo.removeAllItems();
        for (Language language : languageList) {
            idCombo.addItem(language);
        }
        b = true;
    }

    public void check() {
        boolean bool = idText.getText().isEmpty() || nameText.getText().isEmpty();
        if (bool != true) {
            addButton.setEnabled(true);
        } else {
            addButton.setEnabled(false);
        }
    }
}
